/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-primary-container": "#76849f",
                "tertiary-fixed": "#adecff",
                "on-primary-fixed": "#0d1c32",
                "secondary-fixed-dim": "#ffb77d",
                "on-background": "#191c1d",
                "primary": "#000000",
                "secondary": "#904d00",
                "background": "#f8fafa",
                "on-primary-fixed-variant": "#39475f",
                "surface-container-low": "#f2f4f4",
                "surface-dim": "#d8dada",
                "surface": "#f8fafa",
                "primary-container": "#0d1c32",
                "error": "#ba1a1a",
                "on-tertiary": "#ffffff",
                "on-secondary-fixed": "#2f1500",
                "outline": "#75777e",
                "tertiary": "#000000",
                "tertiary-fixed-dim": "#80d2e9",
                "surface-container": "#eceeee",
                "on-secondary-fixed-variant": "#6e3900",
                "tertiary-container": "#001f26",
                "primary-fixed-dim": "#b9c7e4",
                "on-surface-variant": "#44474d",
                "surface-bright": "#f8fafa",
                "on-tertiary-fixed-variant": "#004e5d",
                "on-error-container": "#93000a",
                "on-secondary": "#ffffff",
                "secondary-fixed": "#ffdcc3",
                "on-secondary-container": "#603100",
                "surface-container-highest": "#e1e3e3",
                "surface-tint": "#515f78",
                "on-tertiary-fixed": "#001f26",
                "on-tertiary-container": "#378fa3",
                "error-container": "#ffdad6",
                "surface-container-lowest": "#ffffff",
                "primary-fixed": "#d6e3ff",
                "inverse-on-surface": "#eff1f1",
                "secondary-container": "#fd8b00",
                "inverse-surface": "#2e3131",
                "outline-variant": "#c5c6cd",
                "on-surface": "#191c1d",
                "on-error": "#ffffff",
                "on-primary": "#ffffff",
                "surface-variant": "#e1e3e3",
                "inverse-primary": "#b9c7e4",
                "surface-container-high": "#e6e8e8"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "lg": "32px",
                "margin-mobile": "16px",
                "md": "24px",
                "xl": "48px",
                "xs": "8px",
                "margin-desktop": "40px",
                "sm": "16px",
                "gutter": "20px",
                "base": "4px"
            },
            "fontFamily": {
                "h3": ["Inter"],
                "h1": ["Inter"],
                "body-lg": ["Inter"],
                "body-md": ["Inter"],
                "label-bold": ["Inter"],
                "caption": ["Inter"],
                "h2": ["Inter"],
                "body-sm": ["Inter"],
                "inter": ["Inter", "sans-serif"]
            },
            "fontSize": {
                "h3": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
                "h1": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
                "label-bold": ["14px", { "lineHeight": "1", "fontWeight": "600" }],
                "caption": ["12px", { "lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "500" }],
                "h2": ["32px", { "lineHeight": "1.25", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "body-sm": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }]
            }
        },
    },
    plugins: [],
}
